services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: flashsale
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d flashsale"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr internal://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:9092
    ports:
      - "9092:9092"   # optional, untuk debug dari host
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    ports:
      - "8001:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      KAFKA_TOPIC_RESERVE_REQUESTED: ticket_reserve_requested
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redpanda:
        condition: service_healthy
      redis:
        condition: service_healthy

  inventory:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/inventory
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      KAFKA_TOPIC_RESERVE_REQUESTED: ticket_reserve_requested
      KAFKA_TOPIC_RESERVED: ticket_reserved
      KAFKA_TOPIC_FAILED: ticket_reservation_failed
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy

volumes:
  pgdata:
