from typing import Protocol
from app.domain.entities import Event

class EventRepository(Protocol):
    def add(self, event: Event): ...
    def get(self, event_id: str) -> Event | None: ...
    def save(self, event: Event): ...
